set -g default-terminal "screen-256color"

set -g status-bg colour235
set -g status-fg white

bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -sel clip"

set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# Mac
set -s copy-command 'pbcopy'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'
# Linux
set -s copy-command 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# new window with 2x2 panes
bind g new-window \; split-window -h \; select-pane -t 0 \; split-window -v \; select-pane -t 2 \; split-window -v \; select-pane -t 0

# broadcast to all panes (toggle)
bind b set-window-option synchronize-panes \; display-message "synchronize-panes: #{?synchronize-panes,on,off}"

# fzf session switcher
bind f display-popup -E "~/.local/scripts/tmux-session-switcher.sh"
